import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Image from "next/image";
import Button from "react-bootstrap/Button";
import Form from "react-bootstrap/Form";
import { GrFacebookOption } from "react-icons/gr";
import { AiOutlineGoogle } from "react-icons/ai";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <>
      <Head>
        <title>Rejuvenics | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <div className="container">
          <Row className="justify-content-center gx-0">
            <Col xl={8} lg={8} md={12}>
              <div className="login-page">
                <Row className="justify-content-center gx-0">
                  <Col xl={6} lg={6} md={6}>
                    <Image
                      src="/register.jpeg"
                      role="presentation"
                      width={430}
                      height={900}
                      alt={"Login"}
                    />
                  </Col>
                  <Col xl={6} lg={6} md={6}>
                    <div className="form-section">
                      <h4 className="mb-4">Create account</h4>
                      <Form>
                      <Form.Group className="mb-3" controlId="formBasicName">
                          <Form.Label>Name</Form.Label>
                          <Form.Control
                            type="text"
                            placeholder="Your Name"
                          />
                        </Form.Group>
                        <Form.Group className="mb-3" controlId="formBasicEmail">
                          <Form.Label>Email</Form.Label>
                          <Form.Control
                            type="email"
                            placeholder="Enter email"
                          />
                        </Form.Group>
                        <Form.Group
                          className="mb-3"
                          controlId="formBasicpassword"
                        >
                          <Form.Label>Password</Form.Label>
                          <Form.Control
                            type="password"
                            placeholder="*********"
                          />
                        </Form.Group>
                        <Form.Label>Staff Role</Form.Label>
                        <Form.Select aria-label="Default select example" className="mb-3">
                          <option>Admin</option>
                          <option value="1">CEO</option>
                          <option value="2">Manager</option>
                          <option value="3">Accountant</option>
                          <option value="4">Driver</option>
                          <option value="5">Security Guard</option>
                          <option value="6">Delivery Person</option>
                        </Form.Select>
                        <div key={`default-checkbox`} className="mb-3">
                          <Form.Check // prettier-ignore
                            type={"checkbox"}
                            id={`default-checkbox`}
                            label={`I agree to the privacy policy`}
                          />
                        </div>
                        <Button
                          variant="success"
                          type="submit"
                          className="w-100"
                        >
                          Create account
                        </Button>
                        <hr className="my-5" />
                        <Button
                          variant="light"
                          type="submit"
                          className="w-100 mb-3 fb"
                        >
                          <GrFacebookOption />
                          &#10240;Login With Facebook
                        </Button>
                        <Button
                          variant="light"
                          type="submit"
                          className="w-100 google"
                        >
                          <AiOutlineGoogle />
                          &#10240;Login With Google
                        </Button>
                      </Form>
                      <div className="bottom-link">
                        <Link href={"/"}>Already have an account? Login</Link>
                      </div>
                    </div>
                  </Col>
                </Row>
              </div>
            </Col>
          </Row>
        </div>
      </main>
    </>
  );
}
